;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="ICCharacter.Attack",NewTagName="ICCharacter.Ability.Attack")
+GameplayTagRedirects=(OldTagName="Ability.InCombat",NewTagName="Ability.InOutCombat")
+GameplayTagRedirects=(OldTagName="Ability.LockTarget",NewTagName="Ability.LockTargetSwitch")
+GameplayTagRedirects=(OldTagName="SetByCaller.Invincible",NewTagName="SetByCaller.InvincibleTime")
+GameplayTagRedirects=(OldTagName="State.Block",NewTagName="State.Blocking")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability",DevComment="")
+GameplayTagList=(Tag="Ability.Action",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Block",DevComment="格挡")
+GameplayTagList=(Tag="Ability.Action.Dodge",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Execution",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Action.SwitchWeapon",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Traversal",DevComment="")
+GameplayTagList=(Tag="Ability.Death",DevComment="")
+GameplayTagList=(Tag="Ability.EnemyAttackBase",DevComment="")
+GameplayTagList=(Tag="Ability.LockTargetSwitch",DevComment="")
+GameplayTagList=(Tag="BodyPart.Arm",DevComment="")
+GameplayTagList=(Tag="BodyPart.Head",DevComment="")
+GameplayTagList=(Tag="BodyPart.Leg",DevComment="")
+GameplayTagList=(Tag="BodyPart.Neck",DevComment="")
+GameplayTagList=(Tag="BodyPart.Torso",DevComment="")
+GameplayTagList=(Tag="Character.Samurai.Sheath",DevComment="")
+GameplayTagList=(Tag="Character.Samurai.Unsheath",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AttackHit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.HitFeedback",DevComment="攻击命中反馈")
+GameplayTagList=(Tag="GameplayEffect.Clash",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.DamageApply",DevComment="")
+GameplayTagList=(Tag="SetByCaller.Damage",DevComment="")
+GameplayTagList=(Tag="SetByCaller.InvincibleTime",DevComment="")
+GameplayTagList=(Tag="State.Blocking",DevComment="处于格挡状态")
+GameplayTagList=(Tag="State.Died",DevComment="")
+GameplayTagList=(Tag="State.GetHurt",DevComment="")
+GameplayTagList=(Tag="State.InAiming",DevComment="")
+GameplayTagList=(Tag="State.InAir",DevComment="")
+GameplayTagList=(Tag="State.InCharge",DevComment="")
+GameplayTagList=(Tag="State.InCharge.AttackCharge",DevComment="")
+GameplayTagList=(Tag="State.InCombat",DevComment="处于战斗状态")
+GameplayTagList=(Tag="State.InCombo",DevComment="")
+GameplayTagList=(Tag="State.InDodge",DevComment="")
+GameplayTagList=(Tag="State.InvincibleUncheckable",DevComment="无敌不可选中")
+GameplayTagList=(Tag="State.Jumping",DevComment="")
+GameplayTagList=(Tag="State.LockAttack",DevComment="")
+GameplayTagList=(Tag="State.OnLockTarget",DevComment="处于锁定了敌人的状态")
+GameplayTagList=(Tag="State.OutOfCombat",DevComment="处于脱战状态")
+GameplayTagList=(Tag="Weapon.Bow",DevComment="")
+GameplayTagList=(Tag="Weapon.Bow.Arrow",DevComment="")
+GameplayTagList=(Tag="Weapon.Katana",DevComment="")
+GameplayTagList=(Tag="Weapon.SingleHandedSword",DevComment="")
+GameplayTagList=(Tag="Weapon.Staff",DevComment="")
+GameplayTagList=(Tag="Weapon.SwordShield",DevComment="剑盾")
+GameplayTagList=(Tag="Weapon.Unarmed",DevComment="")

